---
# Source: external-secrets-provider/templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-externalsecrets-provider-backend
    kind: ClusterSecretStore
  target:
    name: aws-credentials
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .crt }}"
        tls.key: "{{ .key }}"
  
  data:
   - remoteRef:
       key: secret/aws-s3-backup
       property: aws_access_key_id
     secretKey: crt
   - remoteRef:
       key: secret/aws-s3-backup
       property: aws_secret_access_key
     secretKey: secretKey
---
# Source: external-secrets-provider/templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rundeck-user-credentials-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-externalsecrets-provider-backend
    kind: ClusterSecretStore
  target:
    name: rundeck-user-credentials-secret
  
  data:
   - remoteRef:
       key: secret/rundeck-user-credentials-secret
       property: userCredentials
     secretKey: userCredentials
