secretStore:
  enabled: false
  vault:
    server: "https://vault.com:8200"
    path:
    tokenSecretRef:
      name: "vault-token"
      key: "token"

externalSecret:
  enabled: true
  name: ""
  refreshInterval: "1m"
  secretStoreName: ""
  targetName: ""
  data: {}
  
  dataFrom: 
  - extract:
      key: provider-key
      version: provider-key-version
      property: provider-key-property
      conversionStrategy: Default
  - find:
      path: path-to-filter
      name:
        regexp: ".*foobar.*"
      tags:
        foo: bar
      conversionStrategy: Unicode
