secretStore:
  enabled: false
  vault:
    server: "https://vault.com:8200"
    path:
    tokenSecretRef:
      name: "vault-token"
      key: "token"

externalSecret:
  enabled: false
  name: ""
  refreshInterval: "1m"
  secretStoreName: ""
  targetName: ""
  data: {}
  data: {}