{{- if .Values.externalSecret.enabled }}
{{- range $externalSecret := .Values.externalSecret.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
spec:
  refreshInterval: {{ $externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ $externalSecret.secretStoreName }}
    kind: {{ $externalSecret.kind }}
  target:
    name: {{ $externalSecret.targetName }}
  {{ with $externalSecret.data }}
  data: {{- toYaml . | nindent 3 }}
  {{- end }}
  {{ with $externalSecret.dataFrom }}
  dataFrom: {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- end }}
{{- end }}
