{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.targetName }}
  data:
  - secretKey: foobar
    remoteRef:
      key: {{ .Values.externalSecret.remotePath }}
      property: {{ .Values.externalSecret.remoteValue }}
{{- end }}