{{- if .Values.externalSecret.enabled }}
{{- range $externalSecret := .Values.externalSecret.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
spec:
  refreshInterval: {{ $externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ $externalSecret.secretStoreName }}
    kind: {{ $externalSecret.kind }}
  target:
    name: {{ $externalSecret.targetName }}
    {{- if ($externalSecret.tls).enabled }}
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ printf "{{ .crt }}" }}"
        tls.key: "{{ printf "{{ .key }}" }}"
    {{- end }}
  {{ with $externalSecret.data }}
  data: {{- toYaml . | nindent 3 }}
  {{- end }}
  {{ with $externalSecret.dataFrom }}
  dataFrom: {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- end }}
{{- end }}
