{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.targetName }}
  {{ with .Values.externalSecret.data }}
  data: {{- toYaml . | nindent 3 }}
  {{- end }}
  {{ with .Values.externalSecret.dataFrom }}
  dataFrom: {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}