{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: {{ .Values.secretStore.kind }}
metadata:
  name: {{ .Release.Name}}-backend
spec:
  provider:
    vault:
      server: {{ .Values.secretStore.vault.server }}
      path: {{ .Values.secretStore.vault.path }}
      version: "v2"
      caProvider:
        # Can be Secret or ConfigMap
        type: {{ .Values.secretStore.ca.type }}
        namespace: {{ .Values.secretStore.ca.namespace }}
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: {{ .Values.secretStore.vault.tokenSecretRef.name }}
          key: {{ .Values.secretStore.vault.tokenSecretRef.key }}
          namespace: {{ .Values.secretStore.vault.tokenSecretRef.namespace }}
{{- end }}