{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name}}-backend
spec:
  provider:
    vault:
      server: {{ .Values.secretStore.vault.server }}
      path: {{ .Values.secretStore.vault.path }}
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: {{ .Values.secretStore.vault.tokenSecretRef.name }}
          key: {{ .Values.secretStore.vault.tokenSecretRef.key }}
{{- end }}