{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: {{ .Values.secretStore.kind }}
metadata:
  name: {{ .Release.Name}}-backend
spec:
  provider:
    vault:
      server: {{ .Values.secretStore.vault.server }}
      path: {{ .Values.secretStore.vault.path }}
      version: "v2"
      {{- if .Values.secretStore.vault.ca.enabled }}
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: {{ .Values.secretStore.vault.tokenSecretRef.name }}
          key: {{ .Values.secretStore.vault.tokenSecretRef.key }}
          namespace: {{ .Values.secretStore.vault.tokenSecretRef.namespace }}
      {{- with .Values.secretStore.vault.ca }}
      caBundle: {{ .caBundle }}
      caProvider:
        key: {{ .caProvider.key }}
        name: {{ .caProvider.name }}
        namespace: {{ .caProvider.namespace }}
        type: Secret
      {{- end }}
      {{- end }}
{{- end }}