{{- if .Values.gateway.enabled }}
{{- with .Values.gateway.rules }}
{{- range . }}
{{- if .protocols.https.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}-tls
  namespace: istio-system
spec:
  secretName: {{ .name }}-tls
  duration: 2160h
  renewBefore: 360h
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  {{- range .protocols.https.tls.dnsNames }}
      - {{ . }}
  {{ end }}
  issuerRef:
    name: {{ .protocols.https.tls.issuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
{{- end }}
{{- end }}
{{- end }}