{{- with .Values.tls }}
{{- range . }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}-tls
  namespace: istio-system
spec:
  secretName: {{ .name }}-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  {{- range .dnsNames }}
      - {{ . -}}
  {{ end }}
  issuerRef:
    name: {{ .issuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
{{- end }}