{{- with .Values.gateway }}
{{- range . }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .name }}-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  {{- with .additionalSelector | default "" }}
    {{ toYaml . }}
  {{- end }}
  servers:
  {{-  toYaml .ports | nindent 3 }} 
{{- end }}
{{- end }}