{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gw
  namespace: istio-system
  labels:
    {{- include "istio-template.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  {{- if .Values.protocols.http.enabled }}
    - port:
        number: {{ .Values.protocols.http.port }}
        protocol: HTTP
        name: http
      hosts:
      {{- range .Values.hosts }}
        - {{ . -}}
      {{ end }}
      tls:
        httpsRedirect: {{ .Values.protocols.http.httpsRedirect }}
  {{- end }}
  {{- if .Values.protocols.https.enabled }}
    - port:
        number: {{ .Values.protocols.https.port }}
        protocol: HTTPS
        name: https
      hosts:
      {{- range .Values.hosts }}
        - {{ . -}}
      {{ end }}
      tls:
        mode: {{ .Values.tls.mode }}
        credentialName: {{ .Release.Name }}-tls
  {{- end }}
{{- end }}