{{- if .Values.gateway.enabled }}
{{- with .Values.gateway.rules }}
{{- range . }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .name }}-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  {{- with .additionalSelector | default "" }}
    {{ toYaml . }}
  {{- end }}
  servers:
  {{- if .protocols.grpc.enabled }}
    - port:
        number: {{ .protocols.grpc.port }}
        protocol: GRPC
        name: grpc
      hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
  {{- end }}
  {{- if .protocols.http.enabled }}
    - port:
        number: {{ .protocols.http.port }}
        protocol: HTTP
        name: http
      hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      tls:
        httpsRedirect: {{ .protocols.http.httpsRedirect }}
  {{- end }}
  {{- if .protocols.https.enabled }}
    - port:
        number: {{ .protocols.https.port }}
        protocol: HTTPS
        name: https
      hosts:
      {{- range .hosts }}
        - {{ . -}}
      {{ end }}
      tls:
        mode: {{ .protocols.https.tls.mode }}
        credentialName: {{ .name }}-tls
  {{- end }}
{{- end }}
{{- end }}
{{- end }}