{{- with .Values.virtualservice }}
{{- range . }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .name }}-vs
spec:
  hosts:
  {{- range .hosts }}
    - {{ . -}}
  {{ end }}
  gateways:
    - istio-system/{{ .gatewayName }}-gw
  {{ with .http }}
  http: {{-  toYaml . | nindent 3 }} 
  {{- end }}
  {{ with .tcp }}
  tcp: {{-  toYaml . | nindent 3 }} 
  {{- end }}
  {{ with .tls }}   
  tls: {{-  toYaml . | nindent 3 }}
  {{- end }}
{{- end }}
{{- end }}