{{- if .Values.virtualservice.enabled }}
{{- with .Values.virtualservice.rules }}
{{- range . }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
<<<<<<< Updated upstream
  name: {{ .Release.Name }}-vs
=======
  name: {{ .name }}-vs
  namespace: {{ .namespace }}
>>>>>>> Stashed changes
spec:
  hosts:
  {{- range .hosts }}
    - {{ . -}}
  {{ end }}
  gateways:
    - istio-system/{{ .gatewayName }}-gw
  {{ with .http }}
  http: {{-  toYaml . | nindent 3 }} 
  {{- end }}
  {{ with .tls }}   
  tls: {{-  toYaml . | nindent 3 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}