{{ range $rules := .Values.rules }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "prometheusrules.name" $ }}-{{ $rules}}
  labels:
    app: {{ template "prometheusrules.name" $ }}-{{ $rules }}
    {{- range $k, $v := $.Values.additionalLabels }}
    {{ $k }}: {{$v}}
    {{- end }}
{{ include "prometheusrules.labels" $ | indent 4 }}
spec:
  {{- $file := print "files/" $rules ".yaml"}}
  {{ range $lines := $.Files.Lines $file }}
  {{  $lines }}
  {{- end -}}
{{- end -}}