
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-cluster-issuer
  namespace: istio-system
spec:
  acme:
    email: {{ .Values.email }}
    server: {{ .Values.acme.server }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-cluster-issuer
    solvers:
    - {{ .Values.challange.type }}:
        {{ .Values.solver.type}}:
        {{- range $k, $v := .Values.config }}
          {{ $k }}: {{$v}}
        {{- end }}
    {{- if .Values.selector.enabled }}
      selector:
        {{ .Values.selector.type }}:
        {{- range $v := .Values.selector.configs }}
        - {{ $v }}
        {{- end }}
    {{- end }}