apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teleport-application.fullname" . }}-configmap
  labels:
    {{- include "teleport-application.labels" . | nindent 4 }}
data:
  teleport.yaml: |
    teleport:
      
      data_dir: /var/lib/teleport-app
      
      auth_token: {{ .Values.token }}
      
      auth_servers:
      - {{ .Values.authServer }}
    auth_service:
      enabled: "no"
    ssh_service:
      enabled: "no"
    proxy_service:
      enabled: "no"
    {{- if .Values.app.enabled }}
    app_service:
      enabled: yes
      debug_app: true
      apps:
      - name: {{ .Values.app.name }}
        uri: {{ .Values.app.uri }}
        public_addr: {{ .Values.app.public_addr }}
        {{- if .Values.app.labels }}
        labels:
          {{- with .Values.app.labels }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if or (.Values.app.headers.enabled) (.Values.app.redirect.enabled) }}
        rewrite:
          {{- if .Values.app.redirect.enabled }}
          redirect:
          {{- with .Values.app.redirect.rules }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.app.headers.enabled }}
          headers:
          {{- with .Values.app.headers.rules }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
        {{- end }}
    {{- end }}

    {{- if .Values.db.enabled }}
    db_service:
      enabled: "yes"
      resources:
      - labels:
          {{- with .Values.db.labels }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      databases:
      - name: {{ .Values.db.name }}
        protocol: {{ .Values.db.protocol }}
        uri: {{ .Values.db.uri }}
        static_labels:
        {{- with .Values.db.static_labels }}
        {{- toYaml . | nindent 12 }}
        {{- end }}
        {{ if .Values.db.gcp.enabled }}
        ca_cert_file: /cloudsql/instance/{{ index .Values "external-secrets-provider" "externalSecret" "secrets" 0 "data" 0 "secretKey" }} 
        # GCP-specific configuration when connecting a Cloud SQL instance.
        gcp:
          # GCP project ID.
          project_id: "{{ .Values.db.gcp.project_id }}"
          # Cloud SQL instance ID.
          instance_id: "{{ .Values.db.gcp.instance_id }}"
        {{- end }}
    {{- end }}
